//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoApp.VisualStudio.Options {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoApp.VisualStudio.Options.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore packages automatically.
        /// </summary>
        public static string Restore_Automatic {
            get {
                return ResourceManager.GetString("Restore_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never check or restore packages automatically.
        /// </summary>
        public static string Restore_DoNothing {
            get {
                return ResourceManager.GetString("Restore_DoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for missing packages but let me choose whether to restore them.
        /// </summary>
        public static string Restore_Notify {
            get {
                return ResourceManager.GetString("Restore_Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All packages have been cleared from the cache..
        /// </summary>
        public static string ShowInfo_ClearPackageCache {
            get {
                return ResourceManager.GetString("ShowInfo_ClearPackageCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some packages were not cleared from the cache..
        /// </summary>
        public static string ShowWarning_ClearPackageCache {
            get {
                return ResourceManager.GetString("ShowWarning_ClearPackageCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feed specified is invalid. Please provide a valid feed..
        /// </summary>
        public static string ShowWarning_InvalidSource {
            get {
                return ResourceManager.GetString("ShowWarning_InvalidSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feed specified cannot be empty. Please provide a valid feed..
        /// </summary>
        public static string ShowWarning_SourceRequried {
            get {
                return ResourceManager.GetString("ShowWarning_SourceRequried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install packages automatically.
        /// </summary>
        public static string Update_Automatic {
            get {
                return ResourceManager.GetString("Update_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never check or install packages automatically.
        /// </summary>
        public static string Update_DoNothing {
            get {
                return ResourceManager.GetString("Update_DoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates but let me choose whether to install them.
        /// </summary>
        public static string Update_Notify {
            get {
                return ResourceManager.GetString("Update_Notify", resourceCulture);
            }
        }
    }
}
