//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoApp.VSE {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoApp.VSE.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon CoApp {
            get {
                object obj = ResourceManager.GetObject("CoApp", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All packages have been cleared from the cache..
        /// </summary>
        public static string Info_ClearPackageCache {
            get {
                return ResourceManager.GetString("Info_ClearPackageCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore missing packages automatically.
        /// </summary>
        public static string Restore_Automatic {
            get {
                return ResourceManager.GetString("Restore_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never check or restore missing packages automatically.
        /// </summary>
        public static string Restore_DoNothing {
            get {
                return ResourceManager.GetString("Restore_DoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for missing packages but let me choose whether to install them.
        /// </summary>
        public static string Restore_Notify {
            get {
                return ResourceManager.GetString("Restore_Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 missing package found. Click to view it..
        /// </summary>
        public static string RestoreAvailable {
            get {
                return ResourceManager.GetString("RestoreAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing 1 missing package....
        /// </summary>
        public static string RestoreInstalling {
            get {
                return ResourceManager.GetString("RestoreInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} missing packages found. Click to view them..
        /// </summary>
        public static string RestoresAvailable {
            get {
                return ResourceManager.GetString("RestoresAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing {0} missing packages....
        /// </summary>
        public static string RestoresInstalling {
            get {
                return ResourceManager.GetString("RestoresInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoApp.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install updates automatically.
        /// </summary>
        public static string Update_Automatic {
            get {
                return ResourceManager.GetString("Update_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never check or install packages automatically.
        /// </summary>
        public static string Update_DoNothing {
            get {
                return ResourceManager.GetString("Update_DoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates but let me choose whether to install them.
        /// </summary>
        public static string Update_Notify {
            get {
                return ResourceManager.GetString("Update_Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 update is available. Click to view it..
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing 1 update....
        /// </summary>
        public static string UpdateInstalling {
            get {
                return ResourceManager.GetString("UpdateInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updates are available. Click to view them..
        /// </summary>
        public static string UpdatesAvailable {
            get {
                return ResourceManager.GetString("UpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing {0} updates....
        /// </summary>
        public static string UpdatesInstalling {
            get {
                return ResourceManager.GetString("UpdatesInstalling", resourceCulture);
            }
        }
    }
}
